### ISSUE TITLE
Files get left behind

### ISSUE THREAD

**Issue by deepgreens** [adammillerio/beets-copyartifacts#7]
copyartifacts leaves folders and files behind during import. I have it enabled as a plugin and this is the relevant part of my config. I've tried it with the extensions wildcard and without. cover.jpg comes in but I'm not sure if that is via copyartifacts or or fetchart.

```
copyartifacts: 
    extensions: .*
    print_ignored: yes
    ext:log: $albumpath/$artist - $album
```
